--select * from HAREKETLER

--CREATE PROCEDURE PROHAREKET
--as
--begin
--select HAREKETLER.HAREKETID, URUNLER.AD, MUSTERI.ADSOYAD, PERSONEL.AD, HAREKETLER.FIYAT from HAREKETLER
--inner join URUNLER
--on URUNLER.ID = HAREKETLER.URUN
--inner join MUSTERI
--on MUSTERI.ID = HAREKETLER.MUSTERI
--inner join PERSONEL
--on PERSONEL.ID = HAREKETLER.PERSONEL
--end;
insert into MUSTERI (ADSOYAD) values ('Aygun Akbas')
select * from MUSTERI
SELECT * FROM HAREKETLER