--select * from TBLHAREKET

--select TBLHAREKET.HAREKETID, TBLURUNLER.URUNAD, TBLMUSTERI.AD + ' ' + SOYAD as 'Musteri Adi' ,TBLPERSONEL.ADSOYAD as 'Personel Adi',TBLHAREKET.FIYAT from TBLHAREKET
--inner join TBLURUNLER
--on TBLURUNLER.URUNID = TBLHAREKET.URUN
--inner join TBLMUSTERI
--on TBLMUSTERI.ID = TBLHAREKET.MUSTERI
--inner join TBLPERSONEL
--on TBLPERSONEL.ID = TBLHAREKET.PERSONEL

--create procedure pro1
--as
--select TBLHAREKET.HAREKETID, TBLURUNLER.URUNAD, TBLMUSTERI.AD + ' ' + SOYAD as 'Musteri Adi' ,TBLPERSONEL.ADSOYAD as 'Personel Adi',TBLHAREKET.FIYAT from TBLHAREKET
--inner join TBLURUNLER
--on TBLURUNLER.URUNID = TBLHAREKET.URUN
--inner join TBLMUSTERI
--on TBLMUSTERI.ID = TBLHAREKET.MUSTERI
--inner join TBLPERSONEL
--on TBLPERSONEL.ID = TBLHAREKET.PERSONEL

select * from TBLHAREKET